eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    # 以端口号注册
    instance-id: bus-service
server:
  port: 8082
spring:
  application:
    name: bus-service
    # 取名字
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/bus?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    mode: HTML
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.32.155
    password: 123456
    database: 0
    connect-timeout: 6000
    timeout: 3000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0
  rabbitmq:
    username: admin
    password: 123456
    virtual-host: /
    listener:
      type: simple
      simple:
        acknowledge-mode: auto
        prefetch: 1
        concurrency: 3
        max-concurrency: 3
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 3000
    port: 5672
    host: 192.168.32.155


mybatis:
  typeAliasesPackage: com.example.study.entiy
  mapper-locations: classpath*:/mapper/*.xml

