eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
spring:
  application:
    name: eureka
server:
  port: 8761

logging:
  level:
    com.netflix: warn

